proyect_tucampo/entorno/tucampo/urls.py
from django.contrib import admin
from django.urls import path
from usuarios.views import *
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',Home, name="home"),
    path('home1',Home1, name="home1"),
    path('frutas/',frutas, name="frutas"),
    path('verduras/',verduras, name="verduras"),
    path('granos/',granos, name="granos"),
    path('leguminosas/',leguminosas, name="leguminosas"),
    path('granos/',granos, name="granos"),
    path('carnes/',carnes, name="carnes"),
    path('abarrotes/',abarrotes, name="abarrotes"),
    path('lacteos/',lacteos, name="lacteos"),
    path('l_lacteos/',l_lacteos, name="l_lacteos"),
    path('l_abarrotes/',l_abarrotes, name="l_abarrotes"),
    path('l_carnes/',l_carnes, name="l_carnes"),
    path('l_leguminosas/',l_leguminosas, name="l_leguminosas"),
    path('l_granos/',l_granos, name="l_granos"),
    path('l_verduras/',l_verduras, name="l_verduras"),
    path('l_frutas/',l_frutas, name="l_frutas"),
    path('vender/',vender, name="vender"),
    path('comprar/',comprar, name="comprar"),
    path('quien/',quien, name="quien"),
    path('productor/',productor, name="productor"),
    path('cliente/',cliente, name="cliente"),
    path('conductor/',conductor, name="conductor"),
    path('ofertas/',ofertas , name="ofertas"),
    path('ayuda/',ayuda, name="ayuda"),
    path('registro_manual/',registro_manual, name="registro_manual"),
    path('agregar_cond/',agregar_cond, name="agregar_cond"),
    path('agregar_usuario/',agregar_usuario, name="agregar_usuario"),
    path('validacion_manual/',validacion_manual, name="validacion_manual"),
    path('logueo_manual/',logueo_manual, name="logueo_manual"),
    path('logueo_exitosos/',logueo_exitosos, name="logueo_exitosos"),
    path('registro_func/',registro_func, name="registro_func"),
    path('soporte/',soporte, name="soporte"),
    path('salir/',salir, name="salir"),
    path('buscador/',buscador, name="buscador"),
    path('registro_productos/',registro_productos, name="registro_productos"),
    path('list_tusproductos/',list_tusproductos, name="list_tusproductos"),
    path('listas/',listas, name="listas"),
   
    
    
    ]       

proyect_tucampo/entorno/usuarios/models.py
from pyexpat import model
from django.db import models

class client(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    identification_card = models.CharField(max_length=10)
    direction =  models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    cell_phone = models.CharField(max_length=11)
    email = models.CharField(max_length=254)
    city = models.CharField(max_length=50)
    password = models.CharField(max_length=254)  
    class Meta:
        db_table ='cliente'

class producer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    identification_card = models.CharField(max_length=10)
    direction =  models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    cell_phone = models.CharField(max_length=11)
    email = models.CharField(max_length=254)
    city = models.CharField(max_length=50)
    password = models.CharField(max_length=254)   
    class Meta:
        db_table ='productor'

class driver(models.Model):
    VEHICLE_TYPE =( 
        ('Pickup', 'Pickup'),
        ('Luv','Luv'),
        ('Turbo', 'Turbo'),
        ('Camion sencillo','Camion'),
        ('Doble troque', 'Doble troque'),
        ('Cuatro manos','Cuatro manos'),
        ('Minimula', 'Minimula'),
        ('Tractomula 2 troques','Tractomula 2 troques'),
        ('Tractomula 3 troques','Tractomula 3 troques'))
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    identification_card = models.CharField(max_length=10)
    direction =  models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    cell_phone = models.CharField(max_length=11)
    email = models.CharField(max_length=254)
    vehicle_type = models.CharField(max_length=254, null=True, choices=VEHICLE_TYPE)
    city = models.CharField(max_length=50)
    year = models.CharField(max_length=4)
    password = models.CharField(max_length=254)

    class Meta:
        db_table ='driver'

class Person(models.Model):
    SHIRT_SIZES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
    )
    name = models.CharField(max_length=60)
    shirt_size = models.CharField(max_length=1, choices=SHIRT_SIZES)

CIUDADS ={
    ('bogota','bogota'),
    ('medellin','medellin'),
    ('cali','cali'),
    ('boyaca','boyaca'),
    ('cucuta','cucuta'),
    ('leticia','leticia'),
    ('rionegro','rionegro'),
    ('apartado','apartado'),
    ('turbo','turbo'),
    ('caucasia','caucasia'),
    ('arauca','arauca'),
    ('barranquilla','barranquilla'),
    ('sabanalarga','sabanalarga'),
    ('girardot','girardot'),
    ('fusagasuga','fusagasuga'),
    ('zipaquira','zipaquira'),
    ('facatativa','facatativa'),
    ('cartagena','cartagena'),
    ('magangue','magangue'),
    ('el carmen de bolivar','el carmen de bolivar'),
    ('tunja','tunja'),
    
}
ROL ={
    ('eres cliente','eres cliente'),
    ('eres productor','eres productor'),
    ('eres conductor','eres conducto')
    
}    

class registro (models.Model):
    username = models.CharField(max_length=254, unique=True)
    password = models.CharField(max_length=254)
    rol = models.CharField(max_length=254, choices=ROL)
    nombres = models.CharField(max_length=254)
    apellidos = models.CharField(max_length=254)
    cedula = models.CharField(max_length=254)
    direcion = models.CharField(max_length=254)
    telefono = models.CharField(max_length=254)
    celular = models.CharField(max_length=254)
    correo = models.CharField(max_length=254)
    ciudad= models.CharField(max_length=40, choices=CIUDADS)

    class Meta:
        db_table ='registro'

    def __str__(self):
        return self.username      

class soporte(models.Model):
    correo = models.CharField(max_length=50)
    comentario = models.CharField(max_length=500)        

    class Meta:
        db_table ='soporte'


ESTADO ={
    ('Disponible','disponible'),
    ('no disponible','no disponible'),
    ('pendiente','pendiente'), 
}  
PRODUCTS_FRUTAS ={
    ('banano','banano'),
    ('fresa','fresa'),
    ('papaya','papaya'),
    ('manzana','manzana'), 
    ('uvas','uvas'),
    ('mandarina','mandarina')
}
CANTIDAS ={
    ('50 kgs','50 kgs'),
    ('60 kgs','60 kgs'),
    ('70 kgs','70 kgs'),
    ('80 kgs','80 kgs'), 
    ('90 kgs','90 kgs'),
    ('100 kgs','100 kgs')
}
SI_NO ={
    ('NO','NO'),
    ('SI','SI'),
}
class registro_producto(models.Model):
    producto = models.CharField(max_length=254, unique=True)
    cantidad = models.CharField(max_length=254)
    precio_kgs = models.CharField(max_length=254, choices=ROL)
    precio_total = models.CharField(max_length=254)
    ciudad = models.CharField(max_length=254)
    cedula = models.CharField(max_length=254)
    direcion = models.CharField(max_length=254)
    telefono = models.CharField(max_length=254)
    celular = models.CharField(max_length=254)
    correo = models.CharField(max_length=254)
    ciudad= models.CharField(max_length=40, choices=CIUDADS)

    class Meta:
        db_table ='registro'

    def __str__(self):
        return self.username

proyect_tucampo/entorno/tucampo/templates/base1.html
{% load static %}
<html>





<head>



    <!-- Bootstrap -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
   
     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     
     <!--'{% static "IMAGES/mango.jpg" %}'-->
    <!-- Styles -->
    <link href="{% static '/css1/gestion.css' %}" rel="stylesheet">
</head>

<body>
   
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Gestión de Pedidos</span>
      </h1>


 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="home.html">Gestión de Pedidos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="home.html">Inicio</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="servicios.html">Servicios</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="tienda.html">Tienda</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="contacto.html">Contacto</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="blog.html">Blog</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}  
        
  {% endblock %}



    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Gestión de Pedidos 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>

</body>


</html>

proyect_tucampo/entorno/tucampo/templates/compra.html
{% extends 'base.html' %}
{% load static %}

{% block title %}tu campo {% endblock %}

{% block content %} 

<br>
<br>
<br>
<br>

{% endblock %}
<br>
<br>
<br>
<br>

proyect_tucampo/entorno/tucampo/templates/granos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}tu campo {% endblock %}

{% block content %} 
<div class="row">
    <div class="col-sm-2">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/pera.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."><h3>Pera</h3></a>
      <div class="card">
        <div class="card-body">
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/manzana.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."><h3>Manzana</h3></a>
        <div class="card-body">
        </div>
      
    </div>
    <div class="col-sm-2">
     
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."><h3>Mango</h3></a>
        <div class="card-body">
        </div>
      
    </div>
    <div class="col-sm-2">
      
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/piña.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="piña"><h3>Piña</h3></a>
        <div class="card-body">
        </div>
      
    </div>
    <div class="col-sm-2">
      
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
      
    </div>
    <div class="col-sm-2">
      
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."><h3>Fresa</h3></a>
        <div class="card-body">
        </div>
      
    </div>
</div>
  
 
  <div class="row">
    <div class="col-sm-2">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/pera.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card">
        <div class="card-body">
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="card">
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/manzana.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="card">
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="card">
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="card">
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="card">
        <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
        <div class="card-body">
        </div>
      </div>
    </div>
</div>


<div class="row">
  <div class="col-sm-2">
    <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/pera.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
    <div class="card">
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/manzana.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-2">
    <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/pera.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
    <div class="card">
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/manzana.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="card">
      <a href="{% url 'l_granos' %}"><img src='{% static "IMAGES/mango.jpg" %}'  width="600px" height="200px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
</div>



{% endblock %}

proyect_tucampo/entorno/tucampo/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}tu campo {% endblock %}

{% block content %} 
<br>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="{% url 'ofertas' %}"><img src="{% static 'IMAGES/ofertas.jpg' %}" class="d-block w-100" alt="..." width="1100px" height="400px"></a>
    </div>
    <div class="carousel-item">
      <img src="{% static 'IMAGES/campo12.jpg' %}" class="d-block w-100" alt="..." width="1100px" height="400px">
    </div>
    <div class="carousel-item">
      <img src="{% static 'IMAGES/tucampo.jpg'  %}" class="d-block w-100" alt="..." width="1100px" height="400px">
    </div>
  </div>
</div>

<br>
<div class="row">
  <div class="col-sm-6">
    <a href="{% url 'frutas' %}"><img src='{% static "IMAGES/frts.jpg" %}'  width="600px" height="300px" class="card-img-top" alt="..."></a>
    <div class="card">
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <a href="{% url 'verduras' %}"><img src='{% static "IMAGES/verds.jpg" %}'  width="600px" height="300px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <a href="{% url 'granos' %}"><img src='{% static "IMAGES/granos.jpg" %}' width="600px" height="300px"  class="card-img-top" alt="..."></a>
    <div class="card">
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <a href="{% url 'leguminosas' %}"><img src='{% static "IMAGES/le.jpg" %}'  width="600px" height="300px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-sm-6">
    <a href="{% url 'carnes' %}"><img src='{% static "IMAGES/carnes.jpg" %}'  width="600px" height="300px" class="card-img-top" alt="..."></a>
    <div class="card">
      <div class="card-body">
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <a href="{% url 'abarrotes' %}"><img src='{% static "IMAGES/abarr1.jpg" %}'  width="600px" height="300px" class="card-img-top" alt="..."></a>
      <div class="card-body">
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <a href="{% url 'lacteos' %}"><img src='{% static "IMAGES/hyl.jpg" %}'  width="600px" height="300px" class="card-img-top" alt="..."></a> 
    <div class="card">
      <div class="card-body">
      </div>
    </div>
  </div>
</div>  

<br>

  <div class="row">
    <div class="col-sm-6">
      <img src='{% static "IMAGES/publicidad1.jpg" %}' class="card-img-top" alt="...">
      <div class="card">
        <div class="card-body">
         
          <p class="card-text">los mejores productos del campo. producidos por manos de nuestros campesinos colombianos apoyanos.</p>
          
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <img src='{% static "IMAGES/publicidad.jpg" %}' class="card-img-top" alt="...">
        <div class="card-body">
          
          <p class="card-text">El sector agropecuario no solo es fundamental para la estabilidad económica y social del país, sino para el bienestar alimentario de todo el planeta.</p>
          
        </div>
      </div>
    </div>
  </div>

{% endblock %}
<br>
<br>
<br>
<br>

proyect_tucampo/entorno/tucampo/templates/l_frutas.html
{% extends 'base.html' %}
{% load static %}

{% block title %}tu campo {% endblock %}

{% block content %} 

<p>estas buscando <strong>{{query}}</strong></p>
{% if productos %}

    <p>Articulos encontrados: {{productos│length}} productos</p>

    <ul>
        {% for productos in productos %}
            <li>

                {{productos.nombre}}
            </li>
        {% endfor %}    
    </ul>

    
{% else %}
    <p>no hay resultados para esta busqueda</p>
{% endif productos %}

{% endblock %}

proyect_tucampo/entorno/tucampo/templates/lista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}tu campo {% endblock %}
{% block content %}       
<br>
<button type="submit" class="btn btn-danger">Danger</button>
<a class="btn btn-danger" href="#" role="button">+ agregark</a>
<br>

    <caption>tus productos</caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">nom</th>
        <th scope="col">categoria</th>
        <th scope="col">acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for productos in products %}
      <tr>
        <th></th>
        <td>{{productos.nombre}}</td>
        <td>{{productos.categoria}}</td>
        <td><button class="btn btn-sm btn-danger"><i class="fa-thin fa-trash-can-list"></i></button></td>
      </tr>
      {% endfor %}
      <tr>
        <th scope="row">2</th>
        <td>Jacob</td>
        <td>Thornton</td>
        <td>@fat</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Larry</td>
        <td>the Bird</td>
        <td>@twitter</td>
      </tr>
    </tbody>
  </table>












{% endblock %}

proyect_tucampo/entorno/tucampo/templates/registrar_productos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}tu campo{% endblock %}

{% block content %}  


 <br>

 <div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Registra aqui tus productos</h3>
            <p>
                <form method="post" action="/registro_productos/">
                    {% csrf_token %}
                    {{ form.as_p }} 
                  
                    <input type="submit" class="btn btn-success" value="registrar">
                    
                    
                </form>            
            </p>
        </div>
    </div>
 </div>

 {% endblock content %}<div class="alert-success" {{ mesage.tags }}> {{message}}</div>

proyect_tucampo/entorno/tucampo/templates/registrar_usuario.html
{% extends 'base.html' %}
{% load static %}
{% block title %}tu campo{% endblock %}

{% block content %}  
<h1>logeo exitoso!!!!!!!!</h1>
{% if messages %}
{% for messages in messages %}
<div class="alert-success" {{ mesage.tags }}>{{message}}</div>
{% endfor %}
{% endif %}
 <br>

 <div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">registro</h3>
            <p>
                <form method="post" action="/agregar_usuario/">
                    {% csrf_token %}
                     <!---- {{ form.as_p}} -->
                     <p class="form-group">
                        <label for="id_firts_name">nombres</label>
                        <input type ="text" class="form-control" name="first_name" value ="" maxlength="150"  autofocus required id="firts_name">                    </p>
                    <p>
                        <label for="id_last_name">Apellidos</label>
                        <input type ="text" class="form-control" name="last_name" value ="" required id="id_last_name">                    </p>
                
                    </p>
                    <p>
                        <label for="id_identification_card">Cedula</label>
                        <input type ="number" class="form-control" name="identification_card" value ="" required id="id_identification_card">
                    </p>
                    <p>
                        <label for="id_direction">Direccion</label>
                        <input type ="text" class="form-control" name="direction" value ="" required id="id_direction">
                    </p>
                    <p>
                        <label for="id_phone">Telefono fijo</label>
                        <input type ="number" class="form-control" name="phone" value ="" maxlength="140" required id="id_phone"  >
                    </p>
                    <p>
                        <label for="id_cell_phone">Celular</label>
                        <input type ="number" class="form-control" name="cell_phone"  maxlength="140" id="id_cell_phone" value="" >
                    </p>
                    <p>
                        <label for="id_email">Correo</label>
                        <input type ="email" class="form-control" name="email" value ="" required id="id_email">
                    </p>
                    <p>
                        <label for="id_city">Ciudad</label>
                        <input type ="text" class="form-control" name="city" value ="" required id="id_city">
                    </p>
                    <p>
                        <label for="id_password">passsword</label>
                        <input type ="password" class="form-control" name="passsword" autocomplete="new-password" required id="id_passsword">
                    </p>
                    <input type="submit" class="btn btn-success" value="crear usuario">
                </form>            
            </p>
        </div>
    </div>
 </div>

 {% endblock content %}